# define the FQDN of servers we call on to provide context in notifications
servers:
    graphite: graphite2.internal.inuits.eu

elasticsearch:
  frontend_url: https://logstash2.inuits.eu/_es/_all/_search?
  result_field_truncate: 200
  num_results: 10
logfile: /tmp/nagios-herald.log
formatter_dir: /usr/local/nagios-herald-formatters
icinga: true
